# Site
repository: SaloM0nk/salom0nk.github.io
favicon: images/SaloMonk.png
description: Personal website showcasing my CV, publications, and professional profile

# Content configuration version
version: 2

# Personal info
name: Timo Salomon
title: Engineer | Researcher | Developer 
email: contact@timosalomon.de

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: timo-salomon-413215312
orcid_username: 0000-0002-8343-0625
github_username: SaloM0nk
# xing_username: Timo_Salomon042561
googlescholar_username: hity4acAAAAJ
additional_links:
- title: Mastodon
  icon: fab fa-mastodon
  url: https://norden.social/@SaloMonk

# About Section
about_title: About Me
about_profile_image: images/profile_ts.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello! I am a researcher, software developer, network architect, and security engineer based in Hamburg, Germany. In May 2025, I changed my name from Timo Häckel to Timo Salomon due to marriage.

  Currently, I am pursuing a doctoral degree in cooperation with the Technical University of Dresden, and Hamburg University of Applied Sciences in Germany. 
  My particular interest is the tightly intertwined safety and security of time-sensitive in-vehicle networks, which I am exploring in the context of different research projects. 
  I am a member of the CoRE and INET working groups at HAW Hamburg, where I develop and maintain open-source frameworks for the OMNeT++ simulator. 

  Approaching my doctorate, I am looking for opportunities to apply my experience to network and security projects in industry. 
  Feel free to explore my work and get in touch.

  ![An image of Hamburg harbour](images/HamburgScape1500x500.jpg "Hamburg")

content:
  - title: Education
    layout: list
    content:
      - layout: left
        title: Ph.D. in Computer Science (IN PROGRESS) 
        sub_title: TU Dresden, Germany
        caption: 2018 - 2026
        description: |
          - Thesis: Security Measures for In-Vehicular Real-Time Networks
          - Supervisor (TU Dresden): Prof. Dr. Matthias Wählisch 
          - Supervisor (HAW Hamburg): Prof. Dr. Thomas C. Schmidt 
          - Research focus: Exploring the tightly intertwined safety and security of time-sensitive in-vehicle networks. See publications below.
      
      - layout: left
        title: M.Sc. in Computer Science
        sub_title: HAW Hamburg, Germany
        caption: 2016 - 2018
        description: |
          - Thesis: Automotive Communication Architectures Supporting Quality-of-Service Agreements 
          - Supervisor: Prof. Dr. Franz Korf 
          - Grade: Excellent
          - ECTS-Grade: "A" - top 10%
      
      - layout: left
        title: B.Sc. in Technical Computer Science
        sub_title: HAW Hamburg, Germany
        caption: 2013 - 2016
        description: |
          - Thesis: Feasibility study for porting a multi-chip e-bike user interface to a current Bluetooth Low Energy single-chip system 
          - Supervisor: Prof. Dr. Stephan Pareigis 
          - Grade: Very Good
          - ECTS-Grade: "A" - top 10%

  - title: Scholarship
    layout: list
    content:
      - layout: left
        title: Student Scholar
        sub_title: Studienstiftung des deutschen Volkes
        caption: 2015 - 2018
        description: |
          Nominated by HAW Hamburg in the 4th Bachelor semester, I was funded until the end of my Master's studies and enjoyed the exchange with other students in the Studienstiftung. 

  - title: Professional Experience
    layout: list
    content:         
      - layout: left
        title: Research Assistant 
        sub_title: TU Dresden
        caption: 2024 - 2026
        description: |
          Researcher, Ph.D. student, and scientific supervision of Bachelor's and Master's students.

          2024 - 2026: Research in the project [Cyber Physical Security Using Radiometry for the Edge (C-ray4edge)](https://www.forschung-it-sicherheit-kommunikationssysteme.de/projekte/cray4edge) funded by the German BMBF. 

      - layout: left
        title: Research Assistant 
        sub_title: HAW Hamburg
        caption: 2018 - 2024
        description: |
          Researcher, Ph.D. student, and scientific supervision of Bachelor's and Master's students.

          2018 - 2022: Research in the project [Security for Vehicular Information (SecVI)](https://secvi.inet.haw-hamburg.de) funded by the German BMBF. 

          2022 - 2024: Research in the project [Innovative Airborne Urban Mobility (i-LUM)](https://i-lum.de) funded by the Hamburg BWFGB within the Hamburg X Initiative. 

      - layout: left
        title: Embedded Developer 
        sub_title: COBI GmbH
        caption: 2015 - 2016
        description: |
          Development of a board computer for e-bikes (see [cobi.bike](http://cobi.bike/de)). 
          
          Working student as embedded developer: C/C++ development, system architecture, control and communication modules. 
          
          Bachelor thesis: Porting the system from a multi-chip to a single-chip solution. Focus on system architecture. 

  - title: Interest and Skills
    layout: text
    content: |
      - Network security design 

      - In-vehicle network architecture 

      - Secure, real-time communication in service-oriented architecture

      - IEEE Time-Sensitive Networking (TSN) 

      - Software-Defined Networking (SDN)

      - Programming languages: C/C++, Python, JAVA, C#, Bash/Shell/PowerShell 

      - Management and organization of groups and teams

      - Excellent written and verbal communication skills (English, German) 

      - Looking for open challenges and networking problems 

      - Characteristics: well organized, determined, committed, team player

  - title: Selected Scientific Publications
    layout: text
    content: | 

      **Negotiating strict latency limits for dynamic real-time services in vehicular time-sensitive networks**  
      T. Salomon, L. Maile, P. Meyer, F. Korf, and T. C. Schmidt  
      Vehicular Communications, vol. 57, p. 100 985, Feb. **2026**. [DOI: 10.1016/j.vehcom.2025.100985](https://doi.org/10.1016/j.vehcom.2025.100985)

      **Securing Future In-Vehicle Networks: Monitoring and Control for Ethernet Backbones**  
      T. Häckel, P. Meyer, F. Korf, and T. C. Schmidt  
      Engineering Safe and Trustworthy Cyber Physical Systems: Essays Dedicated to Werner Damm on the Occasion of His 71st Birthday  
      Eds.: M. Fränzle, J. Niehaus, and B. Westphal, Cham: Springer Nature Switzerland, **2026**, pp. 163-182. [DOI: 10.1007/978-3-031-97537-0_10](https://doi.org/10.1007/978-3-031-97537-0_10)

      **Building Automotive Security on Internet Standards: An Integration of DNSSEC, DANE, and DANCE to Authenticate and Authorize In-Car Services**  
      T. Salomon, M. Mueller, P. Meyer, T. C. Schmidt  
      Preprint on [arXiv:2504.05793](https://arxiv.org/abs/2504.05793)

      **Secure Time-Sensitive Software-Defined Networking in Vehicles**  
      T. Häckel, P. Meyer, F. Korf, T. C. Schmidt  
      IEEE Transactions on Vehicular Technology, Vol. 72, No. 1, pp. 35-51, **2023**. [DOI: 10.1109/TVT.2022.3202368](https://doi.org/10.1109/TVT.2022.3202368)

      **Dynamic Service-Orientation for Software-Defined In-Vehicle Networks**  
      T. Häckel, P. Meyer, M. Mueller, J. Schmitt-Solbrig, F. Korf, T. C. Schmidt  
      Proceedings of the IEEE 97th Vehicular Technology Conference (VTC2023-Spring), pp. 1-5, **2023**. [DOI: 10.1109/VTC2023Spring57618.2023.10199712](https://doi.org/10.1109/VTC2023Spring57618.2023.10199712)
      
      **Strategies for Integrating Control Flows in Software-Defined In-Vehicle Networks and Their Impact on Network Security**  
      T. Häckel, A. Schmidt, P. Meyer, F. Korf, and T. C. Schmidt  
      Proceedings of the 2020 IEEE Vehicular Networking Conference (VNC), pp. 1-8, **2020**. [DOI: 10.1109/VNC51378.2020.9318372](https://doi.org/10.1109/VNC51378.2020.9318372)

      **Software-Defined Networks Supporting Time-Sensitive In-Vehicular Communication**  
      T. Häckel, P. Meyer, F. Korf, and T. C. Schmidt  
      Proceedings of the IEEE 89th Vehicular Technology Conference: VTC2019-Spring, pp. 1-5, **2019**. [DOI: 10.1109/VTCSpring.2019.8746473](https://doi.org/10.1109/VTCSpring.2019.8746473)

      **SDN4CoRE: A Simulation Model for Software-Defined Networking for Communication over Real-Time Ethernet**  
      T. Häckel, P. Meyer, F. Korf, and T. C. Schmidt  
      Proceedings of the 6th International OMNeT++ Community Summit 2019, pp. 24-31, **2019**. [DOI: 10.29007/w71t](https://doi.org/10.29007/w71t)

      For a complete list of publications, please visit the [INET RG Homepage](https://www.inet.haw-hamburg.de/publications/TimoSalomon.html), my [Google Scholar](https://scholar.google.com/citations?user=hity4acAAAAJ), or [ORCID](https://orcid.org/0000-0002-8343-0625).

  - title: Open-Source Projects
    layout: list
    content:
      - layout: left
        title: In-Vehicle Network Simulation
        sub_title: OMNeT++ Models by CoRE RG
        caption: 2016 - 2026
        description: |
          I developed and maintained simulation models for in-vehicle networks within my master's and Ph.D. project. 

          Here some quick links: 
          - [CoRE RG on Github](https://github.com/CoRE-RG)
          - [SDN4CoRE (Software-Defined Networking for Communication over Realtime Ethernet)](https://github.com/CoRE-RG/SDN4CoRE)
          - [SOA4CoRE (Service-Oriented Architecture for Communication over Realtime Ethernet)](https://github.com/CoRE-RG/SOA4CoRE)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
