# Site settings
title: CV & Portfolio
name: Timo Salomon
email: mail@timosalomon.de
description: Personal website showcasing my CV, publications, and professional profile
url: "https://salom0nk.github.io"
baseurl: ""

# Social media profiles
github_username: SaloM0nk
linkedin_username: timo-salomon-413215312/
twitter_username: your-twitter
orcid_id: 0000-0002-8343-0625
google_scholar_id: hity4acAAAAJ

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
